NDefines.NCountry.NAVAL_FORCELIMIT_EXTRA_COST_FACTOR = 5
NDefines.NCountry.LAND_FORCELIMIT_EXTRA_COST_FACTOR = 5
NDefines.NCountry.CORE_LOSE_PRESTIGE = 0

NDefines.NMilitary.BASE_MP_TO_MANPOWER = 0.2
NDefines.NMilitary.CONDOTTIERI_TRADITION_BONUS = 2
NDefines.NMilitary.CONDOTTIERI_PRESTIGE_BONUS = 2

NDefines.NDiplomacy.ANNUL_TREATIES_YEARS = 25
NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -200
NDefines.NDiplomacy.MIN_RELATIONS_TO_SUPPORT_INDEPENDENCE = -200
